all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: root
    ansible_ssh_pass: k8suser

  children:
    master:
      hosts:
        master:
          ansible_host: 192.168.1.101
    nodes:
      hosts:
        node1:
          ansible_host: 192.168.1.102
        node2: 
          ansible_host: 192.168.1.103
